spring.application.name=test

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/songalytics_db
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

#Debug
spring.jpa.show-sql=true